//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Presentation {
    
    private PresentationSlide[] slideField;
    
    private string titleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Slide")]
    public PresentationSlide[] Slide {
        get {
            return this.slideField;
        }
        set {
            this.slideField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PresentationSlide {
    
    private PresentationSlideRichTextBlock[] richTextBlockField;
    
    private string titleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RichTextBlock")]
    public PresentationSlideRichTextBlock[] RichTextBlock {
        get {
            return this.richTextBlockField;
        }
        set {
            this.richTextBlockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PresentationSlideRichTextBlock {
    
    private PresentationSlideRichTextBlockParagraph[] paragraphField;
    
    private string selectionHighlightColorField;
    
    private byte fontSizeField;
    
    private string fontStretchField;
    
    private string fontStyleField;
    
    private string fontWeightField;
    
    private string foregroundField;
    
    private string horizontalAlignmentField;
    
    private string isTextSelectionEnabledField;
    
    private byte lineHeightField;
    
    private string lineStackingStrategyField;
    
    private string marginField;
    
    private byte maxLinesField;
    
    private decimal opacityField;
    
    private byte paddingField;
    
    private string textAlignmentField;
    
    private byte textIndentField;
    
    private string textWrappingField;
    
    private string typographyCapitalsField;
    
    private string verticalAlignmentField;
    
    private string visibilityField;
    
    public PresentationSlideRichTextBlock() {
        this.selectionHighlightColorField = "#FAFBFCFF";
        this.fontSizeField = ((byte)(20));
        this.fontStretchField = "Normal";
        this.fontStyleField = "Normal";
        this.fontWeightField = "Normal";
        this.foregroundField = "#FFFFFFFF";
        this.horizontalAlignmentField = "Left";
        this.isTextSelectionEnabledField = "True";
        this.lineHeightField = ((byte)(10));
        this.lineStackingStrategyField = "";
        this.marginField = "0";
        this.maxLinesField = ((byte)(10));
        this.opacityField = ((decimal)(1.0m));
        this.paddingField = ((byte)(0));
        this.textAlignmentField = "Justify";
        this.textIndentField = ((byte)(0));
        this.textWrappingField = "Wrap";
        this.typographyCapitalsField = "True";
        this.verticalAlignmentField = "Top";
        this.visibilityField = "Visible";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Paragraph")]
    public PresentationSlideRichTextBlockParagraph[] Paragraph {
        get {
            return this.paragraphField;
        }
        set {
            this.paragraphField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("#FAFBFCFF")]
    public string SelectionHighlightColor {
        get {
            return this.selectionHighlightColorField;
        }
        set {
            this.selectionHighlightColorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "20")]
    public byte FontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Normal")]
    public string FontStretch {
        get {
            return this.fontStretchField;
        }
        set {
            this.fontStretchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Normal")]
    public string FontStyle {
        get {
            return this.fontStyleField;
        }
        set {
            this.fontStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Normal")]
    public string FontWeight {
        get {
            return this.fontWeightField;
        }
        set {
            this.fontWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("#FFFFFFFF")]
    public string Foreground {
        get {
            return this.foregroundField;
        }
        set {
            this.foregroundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Left")]
    public string HorizontalAlignment {
        get {
            return this.horizontalAlignmentField;
        }
        set {
            this.horizontalAlignmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("True")]
    public string IsTextSelectionEnabled {
        get {
            return this.isTextSelectionEnabledField;
        }
        set {
            this.isTextSelectionEnabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "10")]
    public byte LineHeight {
        get {
            return this.lineHeightField;
        }
        set {
            this.lineHeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("")]
    public string LineStackingStrategy {
        get {
            return this.lineStackingStrategyField;
        }
        set {
            this.lineStackingStrategyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string Margin {
        get {
            return this.marginField;
        }
        set {
            this.marginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "10")]
    public byte MaxLines {
        get {
            return this.maxLinesField;
        }
        set {
            this.maxLinesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "1.0")]
    public decimal Opacity {
        get {
            return this.opacityField;
        }
        set {
            this.opacityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
    public byte Padding {
        get {
            return this.paddingField;
        }
        set {
            this.paddingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Justify")]
    public string TextAlignment {
        get {
            return this.textAlignmentField;
        }
        set {
            this.textAlignmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
    public byte TextIndent {
        get {
            return this.textIndentField;
        }
        set {
            this.textIndentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Wrap")]
    public string TextWrapping {
        get {
            return this.textWrappingField;
        }
        set {
            this.textWrappingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("Typography.Capitals")]
    [System.ComponentModel.DefaultValueAttribute("True")]
    public string TypographyCapitals {
        get {
            return this.typographyCapitalsField;
        }
        set {
            this.typographyCapitalsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Top")]
    public string VerticalAlignment {
        get {
            return this.verticalAlignmentField;
        }
        set {
            this.verticalAlignmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Visible")]
    public string Visibility {
        get {
            return this.visibilityField;
        }
        set {
            this.visibilityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PresentationSlideRichTextBlockParagraph {
    
    private PresentationSlideRichTextBlockParagraphInlineUIContainer inlineUIContainerField;
    
    private PresentationSlideRichTextBlockParagraphBold boldField;
    
    private PresentationSlideRichTextBlockParagraphRun runField;
    
    private PresentationSlideRichTextBlockParagraphHyperlink hyperlinkField;
    
    private string[] textField;
    
    private byte characterSpacingField;
    
    private byte fontSizeField;
    
    private string fontStretchField;
    
    private string fontStyleField;
    
    private string fontWeightField;
    
    private string foregroundField;
    
    private byte lineHeightField;
    
    private string lineStackingStrategyField;
    
    private string textAlignmentField;
    
    private byte textIndentField;
    
    private string typographyCapitalSpacingField;
    
    public PresentationSlideRichTextBlockParagraph() {
        this.characterSpacingField = ((byte)(0));
        this.fontSizeField = ((byte)(20));
        this.fontStretchField = "Normal";
        this.fontStyleField = "Normal";
        this.fontWeightField = "Normal";
        this.foregroundField = "#FFFFFFFF";
        this.lineHeightField = ((byte)(10));
        this.lineStackingStrategyField = "BlockLineHeight";
        this.textAlignmentField = "Justify";
        this.textIndentField = ((byte)(0));
        this.typographyCapitalSpacingField = "True";
    }
    
    /// <remarks/>
    public PresentationSlideRichTextBlockParagraphInlineUIContainer InlineUIContainer {
        get {
            return this.inlineUIContainerField;
        }
        set {
            this.inlineUIContainerField = value;
        }
    }
    
    /// <remarks/>
    public PresentationSlideRichTextBlockParagraphBold Bold {
        get {
            return this.boldField;
        }
        set {
            this.boldField = value;
        }
    }
    
    /// <remarks/>
    public PresentationSlideRichTextBlockParagraphRun Run {
        get {
            return this.runField;
        }
        set {
            this.runField = value;
        }
    }
    
    /// <remarks/>
    public PresentationSlideRichTextBlockParagraphHyperlink Hyperlink {
        get {
            return this.hyperlinkField;
        }
        set {
            this.hyperlinkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
    public byte CharacterSpacing {
        get {
            return this.characterSpacingField;
        }
        set {
            this.characterSpacingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "20")]
    public byte FontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Normal")]
    public string FontStretch {
        get {
            return this.fontStretchField;
        }
        set {
            this.fontStretchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Normal")]
    public string FontStyle {
        get {
            return this.fontStyleField;
        }
        set {
            this.fontStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Normal")]
    public string FontWeight {
        get {
            return this.fontWeightField;
        }
        set {
            this.fontWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("#FFFFFFFF")]
    public string Foreground {
        get {
            return this.foregroundField;
        }
        set {
            this.foregroundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "10")]
    public byte LineHeight {
        get {
            return this.lineHeightField;
        }
        set {
            this.lineHeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("BlockLineHeight")]
    public string LineStackingStrategy {
        get {
            return this.lineStackingStrategyField;
        }
        set {
            this.lineStackingStrategyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Justify")]
    public string TextAlignment {
        get {
            return this.textAlignmentField;
        }
        set {
            this.textAlignmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
    public byte TextIndent {
        get {
            return this.textIndentField;
        }
        set {
            this.textIndentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("Typography.CapitalSpacing")]
    [System.ComponentModel.DefaultValueAttribute("True")]
    public string TypographyCapitalSpacing {
        get {
            return this.typographyCapitalSpacingField;
        }
        set {
            this.typographyCapitalSpacingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PresentationSlideRichTextBlockParagraphInlineUIContainer {
    
    private PresentationSlideRichTextBlockParagraphInlineUIContainerImage imageField;
    
    /// <remarks/>
    public PresentationSlideRichTextBlockParagraphInlineUIContainerImage Image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PresentationSlideRichTextBlockParagraphInlineUIContainerImage {
    
    private string sourceField;
    
    private byte widthField;
    
    private byte heightField;
    
    private string stretchField;
    
    public PresentationSlideRichTextBlockParagraphInlineUIContainerImage() {
        this.stretchField = "Fill";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Fill")]
    public string Stretch {
        get {
            return this.stretchField;
        }
        set {
            this.stretchField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PresentationSlideRichTextBlockParagraphBold {
    
    private byte fontSizeField;
    
    private string fontStretchField;
    
    private byte characterSpacingField;
    
    private string fontStyleField;
    
    private string foregroundField;
    
    private string typographyCapitalSpacingField;
    
    private string valueField;
    
    public PresentationSlideRichTextBlockParagraphBold() {
        this.fontSizeField = ((byte)(20));
        this.fontStretchField = "Normal";
        this.characterSpacingField = ((byte)(0));
        this.fontStyleField = "Normal";
        this.foregroundField = "#FFFFFFFF";
        this.typographyCapitalSpacingField = "True";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "20")]
    public byte FontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Normal")]
    public string FontStretch {
        get {
            return this.fontStretchField;
        }
        set {
            this.fontStretchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
    public byte CharacterSpacing {
        get {
            return this.characterSpacingField;
        }
        set {
            this.characterSpacingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Normal")]
    public string FontStyle {
        get {
            return this.fontStyleField;
        }
        set {
            this.fontStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("#FFFFFFFF")]
    public string Foreground {
        get {
            return this.foregroundField;
        }
        set {
            this.foregroundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("Typography.CapitalSpacing")]
    [System.ComponentModel.DefaultValueAttribute("True")]
    public string TypographyCapitalSpacing {
        get {
            return this.typographyCapitalSpacingField;
        }
        set {
            this.typographyCapitalSpacingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PresentationSlideRichTextBlockParagraphRun {
    
    private string fontStyleField;
    
    private string fontWeightField;
    
    private byte characterSpacingField;
    
    private byte fontSizeField;
    
    private string fontStretchField;
    
    private string foregroundField;
    
    private string typographyCapitalSpacingField;
    
    private string valueField;
    
    public PresentationSlideRichTextBlockParagraphRun() {
        this.fontStyleField = "Normal";
        this.fontWeightField = "Normal";
        this.characterSpacingField = ((byte)(0));
        this.fontSizeField = ((byte)(20));
        this.fontStretchField = "Normal";
        this.foregroundField = "#FFFFFFFF";
        this.typographyCapitalSpacingField = "True";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Normal")]
    public string FontStyle {
        get {
            return this.fontStyleField;
        }
        set {
            this.fontStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Normal")]
    public string FontWeight {
        get {
            return this.fontWeightField;
        }
        set {
            this.fontWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
    public byte CharacterSpacing {
        get {
            return this.characterSpacingField;
        }
        set {
            this.characterSpacingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(byte), "20")]
    public byte FontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("Normal")]
    public string FontStretch {
        get {
            return this.fontStretchField;
        }
        set {
            this.fontStretchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("#FFFFFFFF")]
    public string Foreground {
        get {
            return this.foregroundField;
        }
        set {
            this.foregroundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("Typography.CapitalSpacing")]
    [System.ComponentModel.DefaultValueAttribute("True")]
    public string TypographyCapitalSpacing {
        get {
            return this.typographyCapitalSpacingField;
        }
        set {
            this.typographyCapitalSpacingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PresentationSlideRichTextBlockParagraphHyperlink {
    
    private string navigateUriField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NavigateUri {
        get {
            return this.navigateUriField;
        }
        set {
            this.navigateUriField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
