//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelatedRecords.Wpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDatasource {
            get {
                return ((string)(this["DefaultDatasource"]));
            }
            set {
                this["DefaultDatasource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DefaultMaxRowCount {
            get {
                return ((int)(this["DefaultMaxRowCount"]));
            }
            set {
                this["DefaultMaxRowCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection SearchValues {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SearchValues"]));
            }
            set {
                this["SearchValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>10</string>
  <string>50</string>
  <string>100</string>
  <string>500</string>
  <string>1000</string>
  <string>5000</string>
  <string>10000</string>
  <string>50000</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MaxRows {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MaxRows"]));
            }
            set {
                this["MaxRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSchemaConstraints {
            get {
                return ((bool)(this["UseSchemaConstraints"]));
            }
            set {
                this["UseSchemaConstraints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>IncludeHeader</string>\r\n  <string>ExcludeHeader</string>\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection CopyModes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CopyModes"]));
            }
            set {
                this["CopyModes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IncludeHeader")]
        public string DefaultCopyMode {
            get {
                return ((string)(this["DefaultCopyMode"]));
            }
            set {
                this["DefaultCopyMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Extended</string>\r\n  <string>Single</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SelectionModes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SelectionModes"]));
            }
            set {
                this["SelectionModes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Extended")]
        public string DefaultSelectionMode {
            get {
                return ((string)(this["DefaultSelectionMode"]));
            }
            set {
                this["DefaultSelectionMode"] = value;
            }
        }
    }
}
