// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>configuration</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net35</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace configuration {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    public partial class CConfiguration {
        
        private List<CConfigurationCDatasource> cDatasourceField;
        
        private List<CConfigurationCDataset> cDatasetField;
        
        public CConfiguration() {
            this.cDatasetField = new List<CConfigurationCDataset>();
            this.cDatasourceField = new List<CConfigurationCDatasource>();
        }
        
        public List<CConfigurationCDatasource> CDatasource {
            get {
                return this.cDatasourceField;
            }
            set {
                this.cDatasourceField = value;
            }
        }
        
        public List<CConfigurationCDataset> CDataset {
            get {
                return this.cDatasetField;
            }
            set {
                this.cDatasetField = value;
            }
        }
    }
    
    public partial class CConfigurationCDatasource {
        
        private string connectionStringField;
        
        private string nameField;
        
        public string ConnectionString {
            get {
                return this.connectionStringField;
            }
            set {
                this.connectionStringField = value;
            }
        }
        
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    public partial class CConfigurationCDataset {
        
        private List<CConfigurationCDatasetCTable> cTableField;
        
        private List<CConfigurationCDatasetRelationship> relationshipField;
        
        private string nameField;
        
        private string dataSourceNameField;
        
        public CConfigurationCDataset() {
            this.relationshipField = new List<CConfigurationCDatasetRelationship>();
            this.cTableField = new List<CConfigurationCDatasetCTable>();
        }
        
        public List<CConfigurationCDatasetCTable> CTable {
            get {
                return this.cTableField;
            }
            set {
                this.cTableField = value;
            }
        }
        
        public List<CConfigurationCDatasetRelationship> Relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
        
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        public string dataSourceName {
            get {
                return this.dataSourceNameField;
            }
            set {
                this.dataSourceNameField = value;
            }
        }
    }
    
    public partial class CConfigurationCDatasetCTable {
        
        private List<CConfigurationCDatasetCTableCColumn> cColumnField;
        
        private string nameField;
        
        public CConfigurationCDatasetCTable() {
            this.cColumnField = new List<CConfigurationCDatasetCTableCColumn>();
        }
        
        public List<CConfigurationCDatasetCTableCColumn> CColumn {
            get {
                return this.cColumnField;
            }
            set {
                this.cColumnField = value;
            }
        }
        
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    public partial class CConfigurationCDatasetCTableCColumn {
        
        private string nameField;
        
        private string dbTypeField;
        
        private bool isPrimaryKeyField;
        
        private bool isForeignKeyField;
        
        private bool isNullableField;
        
        private string defaultValueField;
        
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        public string DbType {
            get {
                return this.dbTypeField;
            }
            set {
                this.dbTypeField = value;
            }
        }
        
        public bool isPrimaryKey {
            get {
                return this.isPrimaryKeyField;
            }
            set {
                this.isPrimaryKeyField = value;
            }
        }
        
        public bool isForeignKey {
            get {
                return this.isForeignKeyField;
            }
            set {
                this.isForeignKeyField = value;
            }
        }
        
        public bool isNullable {
            get {
                return this.isNullableField;
            }
            set {
                this.isNullableField = value;
            }
        }
        
        public string defaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
    }
    
    public partial class CConfigurationCDatasetRelationship {
        
        private string nameField;
        
        private string fromTableField;
        
        private string toTableField;
        
        private string fromColumnField;
        
        private string toColumnField;
        
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        public string fromTable {
            get {
                return this.fromTableField;
            }
            set {
                this.fromTableField = value;
            }
        }
        
        public string toTable {
            get {
                return this.toTableField;
            }
            set {
                this.toTableField = value;
            }
        }
        
        public string fromColumn {
            get {
                return this.fromColumnField;
            }
            set {
                this.fromColumnField = value;
            }
        }
        
        public string toColumn {
            get {
                return this.toColumnField;
            }
            set {
                this.toColumnField = value;
            }
        }
    }
}
