//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trainer.Wpf.VStudio.Tools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Code\\Data")]
        public string SourcePath {
            get {
                return ((string)(this["SourcePath"]));
            }
            set {
                this["SourcePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.xml")]
        public string FileMask {
            get {
                return ((string)(this["FileMask"]));
            }
            set {
                this["FileMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<Component Id="""" Name=""Class"" Action=""Copy"" IsBrowsable=""true"" TargetFile=""$classname$.cs"">
    <Parameter Label=""Namespace"" Name=""$rootnamespace$"" IsVisible=""false"" IsProjectName=""true"" />
    <Parameter Label=""Class Name"" Name=""$classname$"" Value=""Class"" />
    <Code>
      <![CDATA[namespace $rootnamespace$
{
  public class $classname$ 
  {
    public $classname$() 
    {
    }
  }
}]]>
    </Code>
  </Component>")]
        public string DefaultComponent {
            get {
                return ((string)(this["DefaultComponent"]));
            }
            set {
                this["DefaultComponent"] = value;
            }
        }
    }
}
