<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
	<title>$FirstItem.Name;format="toUpper"$ </title>
	<style type="text/css">
		.firstLevelTable { border: 1px dotted gray; margin-top: 20px; }
		.secondLevelTable { border: 1px dotted gray; margin-top: 20px; margin-left: 40px; }
		.thirdLevelTable { border: 1px dotted gray; margin-top: 20px; margin-left: 80px; }
		.fourthLevelTable { border: 1px dotted gray; margin-top: 20px; margin-left: 120px; }
		.fifthLevelTable { border: 1px dotted gray; margin-top: 20px; margin-left: 160px; }
		.sixthLevelTable { border: 1px dotted gray; margin-top: 20px; margin-left: 200px; }
		.seventhLevelTable { border: 1px dotted gray; margin-top: 20px; margin-left: 240px; }
		.eighthLevelTable { border: 1px dotted gray; margin-top: 20px; margin-left: 280px; }
		.ninethLevelTable { border: 1px dotted gray; margin-top: 20px; margin-left: 320px; }
		.tenthLevelTable { border: 1px dotted gray; margin-top: 20px; margin-left: 360px; }
		th { background: Orange; color: White; }
        td { border: 1px dotted gray; }        
        body { font: normal small-caps normal small Arial; }
	</style>
	</head>
	<body>
	
<$Tables>

	<br>
		Generated on $DateCreated;format="yyyy MMM dd"$
	</body>
</html>